Task: Set c.user to None.
Turns out this is documented in ckan/ckan#4247.

As of CKAN 2.8.0 `views/__init__.py` line 101 throws
an error that isn't caught
(`AttributeError: '_Globals' object has no attribute 'user'`).
Setting c.user sets g and c user to None which prevents
the error from being raised. 2.7.3 didn't have this issue.